server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://172.17.0.4:3100/loki/api/v1/push #docker default bridge network

scrape_configs:
- job_name: local
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log 
- job_name: nodejs-logs
  static_configs:
  - targets:
      - localhost
    labels:
      job: nodejs-app
      __path__: /mnt/logs/nodejs/*log #werkt denk niet?
- job_name: "nodelogger-logs"
  static_configs:
  - targets:
      - localhost
    labels:
      job: "nodelogger"
      __path__: "/mnt/efs_volume/nodejs_logs/*.log"
